-- Fresh-install schema for authenticated, fully isolated users.
-- Existing installations should run supabase_multi_user_migration.sql instead.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) <= 200),
  created_at timestamptz not null default now()
);

create table if not exists public.blots (
  id text primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  folder text not null check (char_length(folder) between 1 and 500),
  has_jpg boolean not null default false,
  has_700 boolean not null default false,
  has_800 boolean not null default false,
  created_at timestamptz not null default now(),
  unique (id, owner_id)
);

create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  blot_id text not null,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  protein_name text not null check (char_length(protein_name) between 1 and 200),
  channel text not null check (channel in ('700', '800')),
  bg_axis text not null check (bg_axis in ('leftright', 'topbottom')),
  lanes_json jsonb not null,
  created_at timestamptz not null default now(),
  foreign key (blot_id, owner_id) references public.blots(id, owner_id) on delete cascade
);

-- Stripe webhooks or controlled server jobs may update this table with the
-- service role. Authenticated users can only read their own billing state.
create table if not exists public.billing_accounts (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  price_id text,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_blots_owner_id on public.blots(owner_id);
create index if not exists idx_scans_blot_id on public.scans(blot_id);
create index if not exists idx_scans_owner_id on public.scans(owner_id);

alter table public.profiles enable row level security;
alter table public.blots enable row level security;
alter table public.scans enable row level security;
alter table public.billing_accounts enable row level security;
alter table public.profiles force row level security;
alter table public.blots force row level security;
alter table public.scans force row level security;
alter table public.billing_accounts force row level security;

revoke all on public.profiles, public.blots, public.scans, public.billing_accounts from anon;
grant usage on schema public to authenticated, service_role;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.blots, public.scans to authenticated;
grant select on public.billing_accounts to authenticated;
grant usage, select on sequence public.scans_id_seq to authenticated;
grant select, insert, update, delete on public.profiles, public.blots, public.scans, public.billing_accounts to service_role;
grant usage, select on sequence public.scans_id_seq to service_role;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "blots_select_own" on public.blots;
drop policy if exists "blots_insert_own" on public.blots;
drop policy if exists "blots_update_own" on public.blots;
drop policy if exists "blots_delete_own" on public.blots;
drop policy if exists "scans_select_own" on public.scans;
drop policy if exists "scans_insert_own" on public.scans;
drop policy if exists "scans_update_own" on public.scans;
drop policy if exists "scans_delete_own" on public.scans;
drop policy if exists "billing_select_own" on public.billing_accounts;

create policy "profiles_select_own" on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "blots_select_own" on public.blots for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "blots_insert_own" on public.blots for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "blots_update_own" on public.blots for update to authenticated
  using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "blots_delete_own" on public.blots for delete to authenticated
  using ((select auth.uid()) = owner_id);

create policy "scans_select_own" on public.scans for select to authenticated
  using ((select auth.uid()) = owner_id);
create policy "scans_insert_own" on public.scans for insert to authenticated
  with check ((select auth.uid()) = owner_id);
create policy "scans_update_own" on public.scans for update to authenticated
  using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "scans_delete_own" on public.scans for delete to authenticated
  using ((select auth.uid()) = owner_id);

create policy "billing_select_own" on public.billing_accounts for select to authenticated
  using ((select auth.uid()) = owner_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'western-blots',
  'western-blots',
  false,
  262144000,
  array['application/zip', 'application/x-zip-compressed', 'image/tiff', 'image/jpeg']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "blot_objects_select_own" on storage.objects;
drop policy if exists "blot_objects_insert_own" on storage.objects;
drop policy if exists "blot_objects_update_own" on storage.objects;
drop policy if exists "blot_objects_delete_own" on storage.objects;

create policy "blot_objects_select_own" on storage.objects for select to authenticated
  using (
    bucket_id = 'western-blots'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "blot_objects_insert_own" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'western-blots'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "blot_objects_update_own" on storage.objects for update to authenticated
  using (
    bucket_id = 'western-blots'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'western-blots'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "blot_objects_delete_own" on storage.objects for delete to authenticated
  using (
    bucket_id = 'western-blots'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
